# Generated by Django 2.2.25 on 2021-12-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.TextField(help_text='Coloque o seu nome ou Apelido', max_length=100)),
                ('texto', models.TextField(help_text='Coloque o texto de forma sucinta', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('profissao', models.CharField(max_length=50)),
                ('texto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acesso.Autor')),
            ],
        ),
    ]
