# Generated by Django 2.2.25 on 2021-12-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0002_auto_20211215_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='imagem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acesso.Figura'),
        ),
    ]
