# Generated by Django 2.2.25 on 2021-12-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0003_auto_20211215_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('feliz', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acesso.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='profissional',
            name='image',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.IntegerField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Figura',
        ),
    ]
