# Generated by Django 2.2.25 on 2021-12-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0004_auto_20211215_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(max_length=13),
        ),
    ]
