# Generated by Django 2.2.25 on 2021-12-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0005_auto_20211215_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='feliz',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='nome',
            new_name='identificacao',
        ),
    ]
